import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../globals.css";
import Image from "next/image";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function Layout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={`${inter.className} bg-[#151439] text-white`}>
        <header className="flex justify-center	items-end w-full h-64 relative">
          <Image
            src="/Banner-test.png"
            alt={"Banner image of an abtract map"}
            fill
            className="object-cover"
          />
          <h1 className="z-10 text-7xl ">Projects</h1>
        </header>
        {children}
      </body>
    </html>
  );
}
